package com.test.flow;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solicitud implements java.io.Serializable {

    static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "vehiculo1")
	private java.lang.String vehiculo1;
	@org.kie.api.definition.type.Label(value = "vehiculo2")
	private java.lang.String vehiculo2;
	@org.kie.api.definition.type.Label(value = "vehiculo3")
	private java.lang.String vehiculo3;
	@org.kie.api.definition.type.Label(value = "resultadoVehiculo1")
	private java.lang.String resultadoVehiculo1;
	@org.kie.api.definition.type.Label(value = "resultadoVehiculo2")
	private java.lang.String resultadoVehiculo2;
	@org.kie.api.definition.type.Label(value = "resultadoVehiculo3")
	private java.lang.String resultadoVehiculo3;

	public Solicitud() {
	}

	public java.lang.String getVehiculo1() {
		return this.vehiculo1;
	}

	public void setVehiculo1(java.lang.String vehiculo1) {
		this.vehiculo1 = vehiculo1;
	}

	public java.lang.String getVehiculo2() {
		return this.vehiculo2;
	}

	public void setVehiculo2(java.lang.String vehiculo2) {
		this.vehiculo2 = vehiculo2;
	}

	public java.lang.String getVehiculo3() {
		return this.vehiculo3;
	}

	public void setVehiculo3(java.lang.String vehiculo3) {
		this.vehiculo3 = vehiculo3;
	}

	public java.lang.String getResultadoVehiculo1() {
		return this.resultadoVehiculo1;
	}

	public void setResultadoVehiculo1(java.lang.String resultadoVehiculo1) {
		this.resultadoVehiculo1 = resultadoVehiculo1;
	}

	public java.lang.String getResultadoVehiculo2() {
		return this.resultadoVehiculo2;
	}

	public void setResultadoVehiculo2(java.lang.String resultadoVehiculo2) {
		this.resultadoVehiculo2 = resultadoVehiculo2;
	}

	public java.lang.String getResultadoVehiculo3() {
		return this.resultadoVehiculo3;
	}

	public void setResultadoVehiculo3(java.lang.String resultadoVehiculo3) {
		this.resultadoVehiculo3 = resultadoVehiculo3;
	}
	
	@Override
	public String toString()
	{
	    StringBuilder stringTemp = new StringBuilder();
	    stringTemp.append("Solicidtud:{");
	    stringTemp.append("vehiculo1: " + this.vehiculo1 + ",");
	    stringTemp.append("vehiculo2: " + this.vehiculo2 + ",");
	    stringTemp.append("vehiculo3: " + this.vehiculo3 + ",");
	    stringTemp.append("resultadoVehiculo1: " + this.resultadoVehiculo1 + ",");
	    stringTemp.append("resultadoVehiculo2: " + this.resultadoVehiculo2 + ",");
	    stringTemp.append("resultadoVehiculo3: " + this.resultadoVehiculo3 + ",");
	    stringTemp.append("}");
	    return stringTemp.toString();
	}

	public Solicitud(java.lang.String vehiculo1, java.lang.String vehiculo2,
			java.lang.String vehiculo3, java.lang.String resultadoVehiculo1,
			java.lang.String resultadoVehiculo2,
			java.lang.String resultadoVehiculo3) {
		this.vehiculo1 = vehiculo1;
		this.vehiculo2 = vehiculo2;
		this.vehiculo3 = vehiculo3;
		this.resultadoVehiculo1 = resultadoVehiculo1;
		this.resultadoVehiculo2 = resultadoVehiculo2;
		this.resultadoVehiculo3 = resultadoVehiculo3;
	}

}